[build]
  publish = "dist"
  command = "npm run build"

[dev]
  command = "vite"
  port = 8888
  targetPort = 5173

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200